package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF1A56DB)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE0E7FF)
val onPrimaryContainerLight = Color(0xFF1A56DB)

val secondaryLight = Color(0xFFD97706)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFFBEB)
val onSecondaryContainerLight = Color(0xFFD97706)

val tertiaryLight = Color(0xFF059669)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFECFDF5)
val onTertiaryContainerLight = Color(0xFF059669)

val errorLight = Color(0xFFDC2626)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFEF2F2)
val onErrorContainerLight = Color(0xFFDC2626)

val backgroundLight = Color(0xFFF3F6FA)
val onBackgroundLight = Color(0xFF1E293B)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF1E293B)
val surfaceVariantLight = Color(0xFFF1F5F9)
val onSurfaceVariantLight = Color(0xFF64748B)

val outlineLight = Color(0xFFE2E8F0)
val outlineVariantLight = Color(0xFFF1F5F9)
val scrimLight = Color(0xFF000000)

val inverseSurfaceLight = Color(0xFF1E293B)
val inverseOnSurfaceLight = Color(0xFFF3F6FA)
val inversePrimaryLight = Color(0xFF93C5FD)

val surfaceDimLight = Color(0xFFE2E8F0)
val surfaceBrightLight = Color(0xFFF8FAFC)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8FAFC)
val surfaceContainerLight = Color(0xFFF1F5F9)
val surfaceContainerHighLight = Color(0xFFE2E8F0)
val surfaceContainerHighestLight = Color(0xFFCBD5E1)

val primaryDark = Color(0xFFa6c8ff)
val onPrimaryDark = Color(0xFF002a55)
val primaryContainerDark = Color(0xFF00407a)
val onPrimaryContainerDark = Color(0xFFd5e3ff)
val secondaryDark = Color(0xFFafcccd)
val onSecondaryDark = Color(0xFF1a3435)
val secondaryContainerDark = Color(0xFF314b4c)
val onSecondaryContainerDark = Color(0xFFcbe8e9)
val tertiaryDark = Color(0xFF61dda1)
val onTertiaryDark = Color(0xFF003822)
val tertiaryContainerDark = Color(0xFF005234)
val onTertiaryContainerDark = Color(0xFF7ffabc)
val errorDark = Color(0xFFffb4ab)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000a)
val onErrorContainerDark = Color(0xFFffdad6)
val backgroundDark = Color(0xFF0f1d29)
val onBackgroundDark = Color(0xFFe2ebff)
val surfaceDark = Color(0xFF0f1d29)
val onSurfaceDark = Color(0xFFe2ebff)
val surfaceVariantDark = Color(0xFF414752)
val onSurfaceVariantDark = Color(0xFFc1c6d4)
val outlineDark = Color(0xFF8b919d)
val outlineVariantDark = Color(0xFF414752)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFe2ebff)
val inverseOnSurfaceDark = Color(0xFF0f1d29)
val inversePrimaryDark = Color(0xFF00529a)
val surfaceDimDark = Color(0xFF0f1d29)
val surfaceBrightDark = Color(0xFF354351)
val surfaceContainerLowestDark = Color(0xFF0a1824)
val surfaceContainerLowDark = Color(0xFF0f1d29)
val surfaceContainerDark = Color(0xFF13212d)
val surfaceContainerHighDark = Color(0xFF1e2b38)
val surfaceContainerHighestDark = Color(0xFF283643)
